{"name": "st.family -- @1.1 transfer types", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not iterable\n", "trace": "  File \"c:\\users\\sasa\\anaconda3\\envs\\finbot\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\sasa\\anaconda3\\envs\\finbot\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\charity.py\", line 8, in step_impl\n    assert client.check_message_code(code)\n  File \"C:\\Users\\sasa\\PycharmProjects\\FinBot\\base\\user_telegram.py\", line 110, in check_message_code\n    self.client.loop.run_until_complete(self.async_check_message_code(code))\n  File \"c:\\users\\sasa\\anaconda3\\envs\\finbot\\lib\\asyncio\\base_events.py\", line 587, in run_until_complete\n    return future.result()\n  File \"C:\\Users\\sasa\\PycharmProjects\\FinBot\\base\\user_telegram.py\", line 80, in async_check_message_code\n    for row in self.table:\n"}, "steps": [{"name": "Given client send message -/start-", "status": "passed", "start": 1605218806643, "stop": 1605218809304}, {"name": "And client click the button -Благодійність-", "status": "passed", "start": 1605218809307, "stop": 1605218811876}, {"name": "And client click the button -ST.FAMILY-", "status": "passed", "start": 1605218811878, "stop": 1605218814545}, {"name": "And client send message -запит-", "status": "passed", "start": 1605218814547, "stop": 1605218818586}, {"name": "And client click the button -Відмінити тікет-", "status": "passed", "start": 1605218818588, "stop": 1605218821020}, {"name": "When client click the button -Так-", "status": "passed", "start": 1605218821022, "stop": 1605218824665}, {"name": "Then client check message -Тікет скасований-1138-", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not iterable\n", "trace": "  File \"c:\\users\\sasa\\anaconda3\\envs\\finbot\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\sasa\\anaconda3\\envs\\finbot\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\charity.py\", line 8, in step_impl\n    assert client.check_message_code(code)\n  File \"C:\\Users\\sasa\\PycharmProjects\\FinBot\\base\\user_telegram.py\", line 110, in check_message_code\n    self.client.loop.run_until_complete(self.async_check_message_code(code))\n  File \"c:\\users\\sasa\\anaconda3\\envs\\finbot\\lib\\asyncio\\base_events.py\", line 587, in run_until_complete\n    return future.result()\n  File \"C:\\Users\\sasa\\PycharmProjects\\FinBot\\base\\user_telegram.py\", line 80, in async_check_message_code\n    for row in self.table:\n"}, "start": 1605218824667, "stop": 1605218824966}], "parameters": [{"name": "button", "value": "ST.FAMILY"}], "start": 1605218806641, "stop": 1605218824974, "uuid": "d6f9003c-3359-479f-847a-f20fd4a7eb4f", "historyId": "59b4d465c53b2a663266ce74295d9132", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "sd_test12_bot"}, {"name": "feature", "value": "finbot_spd_charity"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}